sudo: false

language: cpp

compiler:
# - clang
- gcc

addons:
  apt:
    sources:
    - george-edison55-precise-backports
    - ubuntu-toolchain-r-test
    - boost-latest
    packages:
    # - clang-3.7
    - g++-4.9
    - gcc-4.9
    - libboost1.55-all-dev
    - python-pip
    - libffi-dev
    - libssl-dev
    - cmake
    - cmake-data

env:
  matrix:
  # - BUILD_TYPE=Debug
  - BUILD_TYPE=Release
  global:
  - secure: "g+iZw5iuBztrlPegctYgoANAmuQnOM60zAN6XsGswkuRN076WC7J8q1ZoxPfRsk54trWqx3v5o5KZwu9AapvSNiIiaY9KVVoVRNFAP9298GOmN9lTPdkVp/qNBSU5G52mi9ZAy9uzl8Ri31xQbWhg2sfF+kAZV6xh5CMSpHwfXnCYObA/Yn1lvdmwARW6EBEtzheKZf57HBD9FensnhKRgZqw+BcfwcYx2YCTIecywPR4GsxBxNabQdojgUrBRxwNmKixCUjyMoX3WPjbJvoeDTVXoXBRe3QDmIK5QaSa+JGkbw8Hx9BGKuYEUXhJ4xkH3Zqrd5CBAI1k4YFHsSDu+MXmkj0l5/NyvTuhc9SS3NrbNUXJeDSHJqfHPPKT9QjNixwObvrpJcdT4LHH4B/JvMVPfLBDN2XfdoaKtMPAm4i9CabaqhZbQXqKLfV/O3Ai2s0oOLCFBmpxYqIsn+bTD4+Ga8nHUqVIV6+MUF1jWZueP8/RfohHrHC9BqbBeRSG6hKpk/Y3TGvSu25vXt2vNl01mZetdm4Sa7wpQ6BN9YOQqYgBcokGDdqdQQQWSDKtte3wDKOQby27Oo1GrSfWNhLSEKZXjWLrRVya1UO8/JtzaDoRhVjJ5W4Rj4gfpwV8ghsQQKQ/NbmOLtlvfDn+CRtVbG46tTGrDPW3nh538k="
  - secure: "QSS8aCzBwgA8NwXa0SIFRj2L1//fTXRGLr1utGEzSK+iIQ0R3i3SpRakl22JhnHBCXULmW9A0UCgejbn7uM8NtDPBYleldpe+3Yqxk/2a9VO91ETUc6agcpwrGz9B+V03NwpR9G5m9eLaTW5BmgbtrTf0wNOX1ekZF0khb7/bY+EABPrl8ELAQ9VokXy9sDJJmqdjKe3xIPUGs9USgd94g2eHCd7BOvVx2+jMmiXyiu3N4xJipy4XXkihrOqUDP/tbdsYursKBrlE4fXsbI4wq1dF9HeGTugq8glIg417ZaxlkziuBt1qqWf+doCwOnQcYXy4u8aU+4ryRdq6CsvqMCQpS6BTaudgu+PxBtynEHQcx+htEZ3fDkVxHIcZJ/EYbTRAooIWZd5Xx5tSXkQ2c6PC9GmoylBebARf810khpqLNL1q00MvUNlm2ZIQ90Zszsmp3eW566Fnk1nccjviothBYUpX/IedR7URj+qxZj2ozkS1V5YAt6Okg7hb7i4unIcteKxzUiK4twtHIap7fXottYiohsYmn/OXj+MJeX1DbzNOSNNxLFXg8BD/VrRG+4kk6Qr5CIQvh9uhaEtN5kjl/91nfRU0yh5xhPCUsNHC79Kjdc0DWnRFEBfYD1HryfowqcTqwIGhE1Rd4kELB52OIrbxh4ARHKAbtl6QU8="
  - secure: "xlMIUKrUNlSR4IRDg7r6f2R0ly3ULGMLKs8Axeh+bk8d6NCDYI521hhe1wjG2g6leBFYMt0vgnggnZQsvvvFlVX3k++Hs1pOXkeTxpgNliyJPx0bfSI74Ai2JVdATt14XqwAZnzwusRKYyQa0Je3y+yglKy/rgxzbCFibuXrJRkofwmPKz7tvvUGEpJUYgoYjRUTVMu25wPGx4iUwTxNfuvzZhB6XM9mMqH4YTeJwABlqWBsDZN+QSCFTlCXRnyAAGgxKLIDl4B9G5MGIi3w6xfwl/DpFfn0zmfZ4CwaSlFHlFVjzEBAHcKSG5oBshL0qNuZaRJ15ZXKt1qKiyEHAeCpX68kiZyGPPGLBhUWGrCvhjOn+0e4XAJ3NLBV7Z+ZA3PobkQIiGhNhUfBObyMCZv3DLFxv53wWmAx9oHSgY3ERFjMVm4xNrqDpG4ySg8WvQGXHZziLhXcCVCiMNj1/xiv3AlAtHVn8kb1avh6sRlb4XNTYMOmVmg9C2BsGxmoIPys9U8nJHp1azqP8VYvXBk2RsDbwxUGfGs3SLO//u5cI4bfcgoSA6a6OtJPtI3uuO894LjPUGlp4L61AgTg5LMSONt6WYgCNCVrey/JLdd9vq1WpAzhqRpA9/nX+DRO1nYaLp/zYYCiRvCEKVAWMGza6vEzklc117MfUzMp4fs="
  
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.8" CC="clang-3.8"; fi
  - pip install --user --upgrade -r gmusicapi/requirements.txt 
  
script:
  - mkdir _build
  - cd _build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DGM_U=$GM_U -DGM_P=$GM_P -DGM_R=$GM_R
  - make
  - make test ARGS="-V || cat ~/.cache/gmusicapi/log/gmusicapi.log" 
