platform:
  - Win32
  
environment:
  GM_U:
    secure: YqHTlbjExy8+GCV4dmswfn8MiR7ATBOSTJ+ymIQ+I0o=
  GM_P:
    secure: B5Z6Y7b6W5n7SiO0fXa2Kw==
  GM_R:
    secure: pnfZc6rMyfKi6UMBCNLhheHykTx/Yu5nr1xxQuX68YmiGXa30noifm8YZeKJRlkS
  GM_AA_ID:
    secure: lRWdgF+NYnKPwDzQBi4oaYeVkSJgGM+m4Jv5LrhAlgA=
  
  matrix:
    # - PYTHON_DIR: C:\\Python27
      # PYTHON_VERSION: 2.7.12
    - PYTHON_DIR: C:\\Python35
      PYTHON_VERSION: 3.5.2
      
configuration: Release

cache:
  - C:\.hunter

install:
  - git submodule update --init --recursive
  - set PATH=%PYTHON_DIR%;%PYTHON_DIR%\\Scripts;%PATH%
  - appveyor DownloadFile https://bootstrap.pypa.io/get-pip.py
  - python get-pip.py
  - call scripts\install-gmusicapi.bat 

build_script:
  - if "%platform%"=="Win32" set "CMAKE_GENERATOR_NAME=Visual Studio 14 2015"
  - if "%platform%"=="x64" set "CMAKE_GENERATOR_NAME=Visual Studio 14 2015 Win64"
  - cmake . -B_build -G "%CMAKE_GENERATOR_NAME%" -DPYBIND11_PYTHON_VERSION=%PYTHON_VERSION%
  - cmake --build _build --config %CONFIGURATION%
  
test_script:
  - cd _build
  - ctest -C %CONFIGURATION% -VV
  - cd ..

on_failure:
  - set GMUSICAPI_LOG=%LOCALAPPDATA%\Simon Weber\gmusicapi\Logs\gmusicapi.log
  - if exist %GMUSICAPI_LOG% (type %GMUSICAPI_LOG%)
