platform:
  - Win32
  - x64
  
environment:
  GM_U:
    secure: YqHTlbjExy8+GCV4dmswfn8MiR7ATBOSTJ+ymIQ+I0o=
  GM_P:
    secure: B5Z6Y7b6W5n7SiO0fXa2Kw==
  GM_R:
    secure: pnfZc6rMyfKi6UMBCNLhheHykTx/Yu5nr1xxQuX68YmiGXa30noifm8YZeKJRlkS
  GM_AA_ID:
    secure: lRWdgF+NYnKPwDzQBi4oaYeVkSJgGM+m4Jv5LrhAlgA=
  
  matrix:
    - PYTHON: C:\Python27.10
      PYTHON_VERSION: 2.7.10
      
configuration: Release

cache:
  - C:\.hunter

install:
  - git submodule update --init --recursive
  - if "%platform%"=="Win32" set PYTHON_URL=https://www.python.org/ftp/python/2.7.10/python-2.7.10.msi
  - if "%platform%"=="x64" set PYTHON_URL=https://www.python.org/ftp/python/2.7.10/python-2.7.10.amd64.msi
  - appveyor DownloadFile %PYTHON_URL% -FileName python2710.msi
  - msiexec /i python2710.msi /qn /norestart TARGETDIR=%PYTHON%
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - appveyor DownloadFile https://bootstrap.pypa.io/get-pip.py
  - python get-pip.py
  - call scripts\install-gmusicapi.bat 

build_script:
  - if "%platform%"=="Win32" set "CMAKE_GENERATOR_NAME=Visual Studio 14 2015"
  - if "%platform%"=="x64" set "CMAKE_GENERATOR_NAME=Visual Studio 14 2015 Win64"
  - cmake . -B_build -G "%CMAKE_GENERATOR_NAME%" -DCMAKE_BUILD_TYPE=%CONFIGURATION%
  - cmake --build _build --config %CONFIGURATION%
  
test_script:
  - python -c "import gmusicapi; print(gmusicapi.__file__)"
  - cd _build
  - ctest -C %CONFIGURATION% -V
  - cd ..

on_failure:
  - set GMUSICAPI_LOG=%LOCALAPPDATA%\Simon Weber\gmusicapi\Logs\gmusicapi.log
  - if exist %GMUSICAPI_LOG% (type %GMUSICAPI_LOG%)
