platform:
  - Win32
  - x64
  
environment:
  GM_U:
    secure: YqHTlbjExy8+GCV4dmswfn8MiR7ATBOSTJ+ymIQ+I0o=
  GM_P:
    secure: B5Z6Y7b6W5n7SiO0fXa2Kw==
  GM_R:
    secure: pnfZc6rMyfKi6UMBCNLhheHykTx/Yu5nr1xxQuX68YmiGXa30noifm8YZeKJRlkS
  GM_AA_ID:
    secure: lRWdgF+NYnKPwDzQBi4oaYeVkSJgGM+m4Jv5LrhAlgA=
  
  matrix:
    - PYTHON: C:\Python27.10
      PYTHON_VERSION: 2.7.10
      BOOST_ROOT: C:\Libraries\boost_1_59_0
      
configuration: Release

install:
  - git submodule update --init --recursive
  - if "%platform%"=="Win32" set PYTHON_URL=https://www.python.org/ftp/python/2.7.10/python-2.7.10.msi
  - if "%platform%"=="x64" set PYTHON_URL=https://www.python.org/ftp/python/2.7.10/python-2.7.10.amd64.msi
  - appveyor DownloadFile %PYTHON_URL% -FileName python2710.msi
  - msiexec /i python2710.msi /qn /norestart TARGETDIR=%PYTHON%
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - appveyor DownloadFile https://bootstrap.pypa.io/get-pip.py
  - python get-pip.py
  - call scripts\install-gmusicapi.bat 
  # - mkdir depends
  # - cd depends
  # - appveyor DownloadFile http://dependencywalker.com/depends22_x64.zip
  # - 7z e depends22_x64.zip
  # - cd ..

build_script:
  - mkdir _build
  - cd _build
  # We generate project files for Visual Studio 12 because the boost binaries installed on the test server are for Visual Studio 12.
  - if "%platform%"=="Win32" set "CMAKE_GENERATOR_NAME=Visual Studio 14 2015" & set "BOOST_LIBRARYDIR=%BOOST_ROOT%\lib32-msvc-14.0"
  - if "%platform%"=="x64" set "CMAKE_GENERATOR_NAME=Visual Studio 14 2015 Win64" & set "BOOST_LIBRARYDIR=%BOOST_ROOT%\lib64-msvc-14.0"
  - cmake .. -G "%CMAKE_GENERATOR_NAME%" -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%" -DGM_U=%GM_U% -DGM_P=%GM_P% -DGM_R=%GM_R% -DGM_AA_ID=%GM_AA_ID%
  - cmake --build . --config %CONFIGURATION%
  - cd ..
  
test_script:
  - python -c "import sys; print(sys.path)"
  - ctest -C %CONFIGURATION% -V
  # - depends\depends.exe /c /ot dependencies.txt C:\projects\gmusicapi-cpp\_build\test\Release\Tester.exe && exit 0
  # - type dependencies.txt
  # - C:\projects\gmusicapi-cpp\_build\test\Release\Tester.exe "Mobileclient login"

on_failure:
  - set GMUSICAPI_LOG=%LOCALAPPDATA%\Simon Weber\gmusicapi\Logs\gmusicapi.log
  - if exist %GMUSICAPI_LOG% (type %GMUSICAPI_LOG%)
